apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: voting-app-db-secret
  namespace: s12kunballi
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: voting-app-secret-store
    kind: SecretStore
  target:
    name: voting-app-db-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: s12kunballi.wft/voting-app
        property: POSTGRES_PASSWORD
