apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: voting-app-secret-store
  namespace: s12kunballi
spec:
  provider:
    vault:
      server: https://vault-playground.edusuc.net
      path: Dev-secret
      version: v2
      auth:
        userPass:
          path: userpass
          username: s12kunballi.wft
          secretRef:
            name: s12kunballi-vault-auth
            key: password
