apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: voting-app-secret-store
  namespace: s12kunballi
spec:
  provider:
    vault:
      server: https://vault-playground.edusuc.net
      path: Dev-secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: voting-app
          serviceAccountRef:
            name: voting-app
